### ISSUE TITLE
8.0 errer

### ISSUE THREAD

**Issue by levin222** [akretion/connector-search-engine#6]
Hi 
Traceback (most recent call last):
  File "/home/lv/g515.0706/app/levin/OCA.connector/connector/queue/worker.py", line 124, in run_job
    job.perform(session)
  File "/home/lv/g515.0706/app/levin/OCA.connector/connector/queue/job.py", line 467, in perform
    self.result = self.func(session, _self.args, *_self.kwargs)
  File "/home/lv/g515.0706/app/levin/akretion.solerp/solerp/unit/export_synchronizer.py", line 122, in export_record
    res = exporter.run(record_id, fields=fields, model_name=model_name)
  File "/home/lv/g515.0706/app/levin/akretion.solerp/solerp/unit/export_synchronizer.py", line 113, in run
    return SolRExportSynchronizer.add(self.backend_record.location.encode('utf-8'), record)
  File "/home/lv/g515.0706/app/levin/akretion.solerp/solerp/unit/export_synchronizer.py", line 57, in add
    si_item = [SolrInterface(url), 0, []]
  File "/home/lv/g515.0706/runtime/python/lib/python2.7/site-packages/sunburnt-0.6-py2.7.egg/sunburnt/sunburnt.py", line 153, in **init**
    self.init_schema()
  File "/home/lv/g515.0706/runtime/python/lib/python2.7/site-packages/sunburnt-0.6-py2.7.egg/sunburnt/sunburnt.py", line 160, in init_schema
    urlparse.urljoin(self.conn.url, self.remote_schema_file))
  File "/home/lv/g515.0706/runtime/python/lib/python2.7/site-packages/sunburnt-0.6-py2.7.egg/sunburnt/sunburnt.py", line 33, in request
    return self.http_connection.request(_args, *_kwargs)
  File "/home/lv/g515.0706/runtime/python/lib/python2.7/site-packages/httplib2/**init**.py", line 1440, in request
    (scheme, authority, request_uri, defrag_uri) = urlnorm(uri)
  File "/home/lv/g515.0706/runtime/python/lib/python2.7/site-packages/httplib2/**init**.py", line 217, in urlnorm
    raise RelativeURIError("Only absolute URIs are allowed. uri = %s" % uri)
RelativeURIError: Only absolute URIs are allowed. uri = admin/file/?file=schema.xml

I try to "Function export_record" then take the error message like above ?  how can we fit it ?

**Comment by rvalyi** [comment]
@levin222 this sounds more like a sunburnt issue, no? What version of solr server are you using? We tested both on 4.x (in production) and 5.x (little).

**Comment by levin222** [comment]
@rvalyi  I using makuk66/docker-solr:4.10.3 from docker

**Comment by levin222** [comment]
@rvalyi  thanks for your repley , I just install solrerp for odoo . What  Is  the Username AND PASSWORD in the "solr Backends" page?

**Comment by sebastienbeau** [comment]
Issue deprecated due to all change done in 8.0 branch and for now solr version is not more supported
